SELECT   MONTH_DETAILS.MONTH AS MONTH, 
		MONTH_DETAILS.YEAR AS YEAR, 
		MONTH_DETAILS.DEPOSITS - MONTH_DETAILS.WITHDRAWALS AS MONTH_BALANCE FROM
(SELECT	STRFTIME('%m', TRANSDATE) as MONTH, 
		STRFTIME('%Y',TRANSDATE) as YEAR, 
		TOTAL(case when ('Deposit' = TRANSCODE) then TRANSAMOUNT else null end) AS DEPOSITS,
		TOTAL(case when ('Withdrawal' = TRANSCODE) then TRANSAMOUNT else null end) as WITHDRAWALS		
		FROM CHECKINGACCOUNT
		WHERE STATUS <> 'V'
		GROUP BY MONTH, YEAR) as MONTH_DETAILS
ORDER BY MONTH_DETAILS.YEAR, MONTH_DETAILS.MONTH
